name: Convert Env To Appservicesettings
description: A prompt that converts Python environment variables to Azure App Service JSON settings format.
model: gpt-4o-mini
modelParameters:
  max_tokens: 4096
messages:
- role: system
  content: "You convert python environment variables to Azure App Service JSON settings.\nBelow is a key-value pair that needs to be converted to JSON.\nThe output is a prettified format of JSON.\n\nEXAMPLE INPUT:\n# AzureOpenAI loads these variables\nOPENAI_API_TYPE = \"azure\"\nOPENAI_API_VERSION = \"2023-05-15\"\n\n# GPT model config\nMAX_TOKENS = 100\n\nEXAMPLE OUTPUT:\n[\n    {\n      \"name\": \"OPENAI_API_TYPE\",\n      \"value\": \"azure\",\n      \"slotSetting\": false\n    },\n    {\n      \"name\": \"OPENAI_API_VERSION\",\n      \"value\": \"2023-05-15\",\n      \"slotSetting\": false\n    },\n    {\n      \"name\": \"MAX_TOKENS\",\n      \"value\": \"100\",\n      \"slotSetting\": false\n    }\n]"
- role: user
  content: Please generate the output based on the context provided.
testData:
- INPUT: '# Database settings DB_CONNECTION_STRING = "Server=production.database.windows.net;Database=maindb;User ID=dbadmin;Password=secureP@ss!123;" DB_MAX_CONNECTIONS = 100

    # Azure Storage STORAGE_ACCOUNT_NAME = "prodstorageaccount" STORAGE_ACCOUNT_KEY = "abcd1234xyz789=="

    '
